version: '3.8'

services:
  development:
    ports: 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.development

  production:
    ports: 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
